[project]
name = "fine-tuning-qwen2-5-docstring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "datasets>=4.4.1",
    "dotenv>=0.9.9",
    "openai>=2.13.0",
]
